[[key_bindings]]
key = "H"
mods = "Alt"
chars = "\u001bh"

[[key_bindings]]
key = "J"
mods = "Alt"
chars = "\u001bj"

[[key_bindings]]
key = "K"
mods = "Alt"
chars = "\u001bk"

[[key_bindings]]
key = "L"
mods = "Alt"
chars = "\u001bl"

[[key_bindings]]
key = "N"
mods = "Alt"
chars = "\u001bn"

[[key_bindings]]
key = "P"
mods = "Alt"
chars = "\u001bp"

[[key_bindings]]
key = "S"
mods = "Alt"
chars = "\u001bs"

[[key_bindings]]
key = "R"
mods = "Alt"
chars = "\u001br"

[[key_bindings]]
key = "T"
mods = "Alt"
chars = "\u001bt"

[[key_bindings]]
key = "W"
mods = "Alt"
chars = "\u001bw"

[[key_bindings]]
key = "X"
mods = "Alt"
chars = "\u001bx"

[[key_bindings]]
key = "Backslash"
mods = "Alt"
chars = "\u001b\\"

[[key_bindings]]
key = "H"
mods = "Alt|Shift"
chars = "\u001bH"

[[key_bindings]]
key = "J"
mods = "Alt|Shift"
chars = "\u001bJ"

[[key_bindings]]
key = "L"
mods = "Alt|Shift"
chars = "\u001bL"

[[key_bindings]]
key = "K"
mods = "Alt|Shift"
chars = "\u001bK"

[[key_bindings]]
key = "N"
mods = "Alt|Shift"
chars = "\u001bN"

[[key_bindings]]
key = "Backslash"
mods = "Alt | Shift"
chars = "\u001b|"

[[key_bindings]]
key = "A"
mods = "Command"
chars = "\u0001"

[[key_bindings]]
key = "B"
mods = "Command"
chars = "\u0002"

[[key_bindings]]
key = "C"
mods = "Command"
chars = "\u0003"

[[key_bindings]]
key = "E"
mods = "Command"
chars = "\u0005"

[[key_bindings]]
key = "F"
mods = "Command"
chars = "\u0006"

[[key_bindings]]
key = "G"
mods = "Command"
chars = "\u0007"

[[key_bindings]]
key = "H"
mods = "Command|Shift"
chars = "\b"

[[key_bindings]]
key = "L"
mods = "Command"
chars = "\f"

[[key_bindings]]
key = "N"
mods = "Command"
chars = "\u000e"

[[key_bindings]]
key = "P"
mods = "Command"
chars = "\u0010"

[[key_bindings]]
key = "R"
mods = "Command"
chars = "\u0012"

[[key_bindings]]
key = "S"
mods = "Command"
chars = "\u0013"

[[key_bindings]]
key = "V"
mods = "Command"
chars = "\u0016"

[[key_bindings]]
key = "V"
mods = "Command|Shift"
action = "Paste"

[[key_bindings]]
key = "W"
mods = "Command"
chars = "\u0017"

[[key_bindings]]
key = "Backslash"
mods = "Command"
chars = "\u001c"

[[key_bindings]]
key = "Slash"
mods = "Command"
chars = "\u001f"

