use_starship = true
path = ["/usr/local/bin", "/usr/local/sbin", "/usr/bin", "/usr/lib/jvm/default/bin", "/usr/bin/site_perl", "/usr/bin/vendor_perl", "/usr/bin/core_perl", "/home/nishan/.local/bin", "/home/nishan/.cargo/bin"]
startup = ["alias edit [file] { nvim $file }", "alias suedit [file] {sudo nvim $file}"]

[env]
SHELL = "/bin/nu"
SESSION_MANAGER = "local/archryzen:@/tmp/.ICE-unix/1199,unix/archryzen:/tmp/.ICE-unix/1199"
WINDOWID = "39845890"
COLORTERM = "truecolor"
XDG_MENU_PREFIX = "gnome-"
TMUX = "/tmp/tmux-1000/default,20331,0"
SSH_AUTH_SOCK = "/run/user/1000/keyring/ssh"
DESKTOP_SESSION = "gnome"
PWD = "/home/nishan/Documents/books"
LOGNAME = "nishan"
XDG_SESSION_DESKTOP = "gnome"
XDG_SESSION_TYPE = "x11"
XAUTHORITY = "/run/user/1000/gdm/Xauthority"
GJS_DEBUG_TOPICS = "JS ERROR;JS LOG"
WINDOWPATH = "2"
GDM_LANG = "en_US.UTF-8"
HOME = "/home/nishan"
USERNAME = "nishan"
LANG = "en_US.UTF-8"
XDG_CURRENT_DESKTOP = "GNOME"
STARSHIP_SHELL = ""
INVOCATION_ID = "4478c92a11654cb2bce44c9e3f42ea99"
MANAGERPID = "1131"
GJS_DEBUG_OUTPUT = "stderr"
XDG_SESSION_CLASS = "user"
TERM = "screen"
USER = "nishan"
TMUX_PANE = "%0"
DISPLAY = ":1"
SHLVL = "1"
XDG_RUNTIME_DIR = "/run/user/1000"
JOURNAL_STREAM = "8:26254"
ALACRITTY_LOG = "/tmp/Alacritty-20321.log"
GDMSESSION = "gnome"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
MAIL = "/var/spool/mail/nishan"
GIO_LAUNCHED_DESKTOP_FILE_PID = "20321"
GIO_LAUNCHED_DESKTOP_FILE = "/home/nishan/.local/share/applications/Alacritty.desktop"
_ = "/bin/nu"
CARGO_TARGET_DIR="/home/nishan/.cargo/target"
