prompt = "echo $(starship prompt)"
startup = ["alias edit = nvim", "alias suedit = sudo nvim", "alias pac = paru", "alias sys = sudo systemctl", "alias cat = bat -p"]

[env]
CARGO_TARGET_DIR = "/home/nishan/.cargo/target"
