set -g default-terminal "tmux-256color"
set -g terminal-overrides ',xterm-256color:Tc'  
set -g default-shell "/bin/zsh"
set -g default-command "/opt/homebrew/bin/nu"

set -g status off
set -g mouse on
set -sg escape-time 0
set -g allow-passthrough on

set-window-option -g mode-keys vi

# Navigate panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D
bind h select-pane -L
bind l select-pane -R
bind j select-pane -U
bind k select-pane -D

# Resize panes
bind -n M-H resize-pane -L
bind -n M-L resize-pane -R
bind -n M-K resize-pane -U
bind -n M-J resize-pane -D
bind H resize-pane -L
bind L resize-pane -R
bind K resize-pane -U
bind J resize-pane -D

# Create / close panes and windows
bind -n M-- split-window -v -c "#{pane_current_path}"
bind -n M-= split-window -h -c "#{pane_current_path}"
bind -n M-x kill-pane
bind -n M-N new-window -c "#{pane_current_path}"
bind \- split-window -v -c "#{pane_current_path}"
bind = split-window -h -c "#{pane_current_path}"
bind \\ choose-buffer
bind x kill-pane
bind N new-window -c "#{pane_current_path}"

# Manage panes and windows (layout / swap / rename)
bind -n M-t next-layout
bind -n M-s swap-pane -D
bind -n M-r command-prompt -I "#W" "rename-window '%%'"
bind t next-layout
bind s swap-pane -D
bind r command-prompt -I "#W" "rename-window '%%'"

# Navigate windows and choose tree
bind -n M-n next-window
bind -n M-p last-window
bind -n M-w choose-tree -Zw
bind n next-window
bind p last-window
bind w choose-tree -Zw
